### ISSUE TITLE
Problem "No section"

### ISSUE THREAD

**Issue by Nico-GS** [Fau46/clisw#1]
Hello,
I tested your program, but I have the same program as the non CLI version.

Indeed when I want to launch the program, I end up with this error:

```
Welcome to isw_cli

This is your pc code: 16W1EMS1
Traceback (most recent call last):
  File "/usr/bin/clisw", line 331, in <module>
    main()
  File "/usr/bin/clisw", line 72, in main
    read_config(pc_code) 
  File "/usr/bin/clisw", line 157, in read_config
    address_profile = cfgp.get(pc_code,"address_profile")
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: '16W1EMS1'
```

I do not understand this error, the program detects the model of my machine, but does not work.

Can you help me ?
thank you so much

**Comment by FauFra** [comment]
Did you install isw from AUR? If is this the case, try to copy this [configuration](https://github.com/YoyPa/isw/blob/master/etc/isw.conf) on etc folder. The AUR version of isw is an old version and probably there isn't your laptop in the file.
